version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://webdev_6uyu_user:wnQQ3GGapKL2K6E3A8atgL44xa5LlWXZ@dpg-cuqnhqrv2p9s73fgrvk0-a.singapore-postgres.render.com/webdev_6uyu
      - PORT=8080
    command: sh -c "
      if [[ $(df -h / | awk 'NR==2 {print $4}' | sed 's/G//') -lt 1 ]]; then
        echo 'Not enough disk space. Skipping database migrations and seeding.';
      else
        echo 'Running database migrations and seeding...';
        npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all || echo 'Database migration or seeding failed. Continuing...';
      fi;
      echo 'Starting application...';
      npm start"
